Fetch and process information by using you tube api
SOEN6441-FALL2024/TubeLytics pull request #17
Opened 2024-10-16 15:27 UTC by Marjan1371

2024-10-17 05:22 UTC, Marjan1371 commented
Added YouTube API integration and updated routes, services, and views

2024-10-24 20:58 UTC, denzz312 requested changes

2024-10-24 20:58 UTC, denzz312 commented on .github/workflows/build.yml
> +      # نصب جاوا 17
Please only add English comments

2024-10-24 20:58 UTC, denzz312 commented on app/controllers/YouTubeController.java
> +  public YouTubeController(YouTubeService youTubeService, ExecutionContext ec) { // تغییر
please only add English comments

2024-10-24 20:58 UTC, denzz312 commented on build.sbt
> +  "org.junit.jupiter" % "junit-jupiter-api" % "5.10.2" % Test,  // اضافه کردن junit-jupiter-api فقط برای تست
please leave the comments in English

2024-10-24 20:58 UTC, denzz312 commented on test/models/VideoTest.java
> +        // بررسی برابر بودن hashCode برای ویدیوهای مشابه
Same as previous comments

2024-10-24 23:49 UTC, denzz312 commented
new pr is created https://github.com/SOEN6441-FALL2024/TubeLytics/pull/18

2024-10-24 23:49 UTC, closed without merging